// rag-platform/frontend/src/App.vue
<script setup>
import { computed, ref } from "vue";
import { useRoute } from "vue-router";
import { theme } from "ant-design-vue";
import { getApiKey, setApiKey } from "./api";

const route = useRoute();

const selectedKeys = computed(() => (route.path.startsWith("/chat") ? ["chat"] : ["home"]));

const keyInput = ref(getApiKey() || "");

function saveApiKey() {
  setApiKey(keyInput.value.trim() || null);
  keyInput.value = getApiKey() || "";
}
</script>

<template>
  <a-config-provider :theme="{ algorithm: theme.defaultAlgorithm }">
    <a-layout style="min-height: 100%">
      <a-layout-header style="display: flex; align-items: center; gap: 16px; padding-inline: 16px">
        <a-typography-text style="color: #fff; font-weight: 600; white-space: nowrap">
          RAG 平台
        </a-typography-text>
        <a-menu
          :selected-keys="selectedKeys"
          theme="dark"
          mode="horizontal"
          :style="{ flex: 1, minWidth: 0, lineHeight: '64px', borderBottom: 'none' }"
        >
          <a-menu-item key="home">
            <router-link to="/">知识库</router-link>
          </a-menu-item>
          <a-menu-item key="chat">
            <router-link to="/chat">对话</router-link>
          </a-menu-item>
        </a-menu>
        <a-space-compact style="max-width: 280px">
          <a-input-password v-model:value="keyInput" placeholder="X-API-Key（可选）" />
          <a-button type="primary" @click="saveApiKey">保存</a-button>
        </a-space-compact>
      </a-layout-header>
      <a-layout-content :style="{ background: route.path === '/chat' ? '#fff' : '#f5f5f5' }">
        <div v-if="route.path === '/chat'" style="background: #fff; min-height: calc(100vh - 64px)">
          <router-view />
        </div>
        <router-view v-else />
      </a-layout-content>
    </a-layout>
  </a-config-provider>
</template>

// rag-platform/frontend/src/App.tsx
import { Layout, Menu, Typography, Input, Space, Button } from "antd";
import { Link, Navigate, Route, Routes, useLocation } from "react-router-dom";
import { useState } from "react";
import KbListPage from "./pages/KbListPage";
import KbDocsPage from "./pages/KbDocsPage";
import ChatPage from "./pages/ChatPage";
import { getApiKey, setApiKey } from "./api";

const { Header, Content } = Layout;

function AppMenu() {
  const loc = useLocation();
  const selected = loc.pathname.startsWith("/chat") ? ["chat"] : ["home"];
  return (
    <Menu
      theme="dark"
      mode="horizontal"
      selectedKeys={selected}
      items={[
        { key: "home", label: <Link to="/">知识库</Link> },
        { key: "chat", label: <Link to="/chat">对话</Link> },
      ]}
      style={{ flex: 1, minWidth: 0 }}
    />
  );
}

export default function App() {
  const [keyInput, setKeyInput] = useState(getApiKey() || "");

  return (
    <Layout style={{ minHeight: "100%" }}>
      <Header style={{ display: "flex", alignItems: "center", gap: 16, paddingInline: 16 }}>
        <Typography.Text style={{ color: "#fff", fontWeight: 600, whiteSpace: "nowrap" }}>
          RAG 平台
        </Typography.Text>
        <AppMenu />
        <Space.Compact style={{ maxWidth: 280 }}>
          <Input.Password
            placeholder="X-API-Key（可选）"
            value={keyInput}
            onChange={(e) => setKeyInput(e.target.value)}
            visibilityToggle
          />
          <Button
            type="primary"
            onClick={() => {
              setApiKey(keyInput.trim() || null);
              setKeyInput(getApiKey() || "");
            }}
          >
            保存
          </Button>
        </Space.Compact>
      </Header>
      <Content style={{ background: "#f5f5f5" }}>
        <Routes>
          <Route path="/" element={<KbListPage />} />
          <Route path="/kb/:kbId" element={<KbDocsPage />} />
          <Route
            path="/chat"
            element={
              <div style={{ background: "#fff", minHeight: "calc(100vh - 64px)" }}>
                <ChatPage />
              </div>
            }
          />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </Content>
    </Layout>
  );
}
